### ISSUE TITLE
What about zprint configuration?

### ISSUE THREAD

**Issue by kkinnear** [clj-commons/zprint-clj#3]
First, thanks for getting this (and `zprint-atom`) going.  I really appreciate it, and I'm sure others do too.  I've learned a lot just testing and trying things with what you and @thheller have done with node. 

 I'm wondering if there is a way to pass configuration `zprint-clj` or `zprint-atom`?  Part of the strength of zprint is that people want it "their way", and if one wants to take the time, zprint will pretty much let you have it your way.  The npm  [package](https://github.com/thheller/zprint-npm) that @thheller did let's you have an options map on the command line, and reads the `~/.zprintrc` file as well.  Is there any chance that you could pick up some of that capability into `zprint-clj`?  If `zprint-clj` had this, I expect that `zprint-atom` would at least pick up the `~/.zprintrc` capability, if not the command line options map as well.

Were your code in .cljs, I'd probably try my hand at moving replicating what @thheller did and send you a pull request, but I remain inexperienced with doing this stuff in .js.

I'm thinking of doing a bit of an announcement of zprint (which I do about every six months), and it would be nice to point to `zprint-clj` and '`zprint-atom` and say that they not only did zprint but would use your default configuration as well.

In the spirit of full disclosure, the other reason I care about allowing people to configure zprint is that having `zprint-clj` have hang be default off makes me cringe.  I think the resulting code look terrible.  I'm not arguing that you should enable it by default (though I'm _barely_ holding myself back on that).  But I have created a style `{:style :no-hang}` in 0.4.7 which you could use to turn it off.   I will also create a style `{:style :all-hang}` which people could use to turn it back on in their `~/.zprintrc`.  But of course this is only useful if `zprint-clj` actually reads the `~/.zprintrc`, and allows what is read-in to supplant whatever defaults were already configured.  I'd like to be able to tell people that they could easily configure `zprint-clj` and `zprint-atom` to have hang enabled with something simple in their `~/.zprintrc`.  Otherwise I imagine that I'm going to fall all over myself apologizing for the awful way the code looks without `:hang` enabled!

Thanks for considering this!

**Comment by codeGlaze** [comment]
+1 for config

But, that's actually just a reason to drop a **huge** thank you @roman01la !
This is the first formatter I've found that actually worked on my system. <3 Thank you!

**Comment by roman01la** [comment]
@kkinnear Sorry I didn't respond earlier. I agree that configuration might be fine. Could you please list what exactly you think should be added/changed? I might take a look when I have time. Thanks!

**Comment by kkinnear** [comment]
Functionally, I'm hoping for four changes to zprint-clj:
1. Read the file `~/.zprintrc` and call `set-options!` with the result.
2. Get a string from the command line, call `cljs.reader\read-string` on it, and call `set-options!` with the result.
3. Accept a file from `stdin` and write the result to `stdout`.  This makes it easy to use as a filter from any number of programs, including many editors (like the one I use).
4. Three (mutually exclusive) possibilities for `--hang`:
   - Remove `--hang` from the UI, and don't call `set-options!` with the options map you are using now to remove all hangs.  If people want to configure `zprint-clj` without hangs, they can just configure the `~/.zprintrc` file with `{:style :no-hang}`, or put that options map on the command line.  This would be my preference.  It actually isn't the major UI change that it could be, since you don't document `--hang` explicitly in the readme, you have to read the .js code to see it.
   - If someone specified `-i` or `-o`, then call `(set-options! {:style :no-hang}`, so they get the current behavior if they use the current command line switches, but if they use `stdin` and `stdout`, they get the normal defaults -- which they can change in `~/.zprintrc` and on the command line.
   - Before doing anything else, call `(set-options! {:style :no-hang}`, which makes no hanging the default but allows people to override that.

I would think that you could keep the current `-i` and `-o` user interface if you wanted to.  Presumably you would use the file from `-i` instead of `stdin` and the file from `-o` instead of `stdout` if the switches were specified.

I was unable to hack something together quickly to do this in your existing .js main program, or I would have done so and sent it to you.  The .cljs main program in @thheller [package](https://github.com/thheller/zprint-npm) does much of what I've described in .cljs (without preserving your current command line switches, of course).

Thanks!

**Comment by roman01la** [comment]
Resolved by #4
