### ISSUE TITLE
support directory.

### ISSUE THREAD

**Issue by netpyoung** [clj-commons/zprint-clj#5]
currently this project support on file.
but I want to apply zprint-clj on our project for code standard.

**Comment by tmattacchione** [comment]
@netpyoung do you mean you want to automatically run this over every file in your project in one go to sync them all with the code standard you define?

**Comment by netpyoung** [comment]
Um. It will be good for support leiningen or boot or clj project. But what I want is support files on user specific directory.

Currently it seems like only one file
`zprint-clj -i <file> -o <file>`

How about like this
`zrint-clj -d <dir> --force --opt style.edn`

**Comment by filipesilva** [comment]
This is also something I'd like to do, to enforce formatting in a whole project.

**Comment by roman01la** [comment]
I'd say that it's totally possible to have clj script that uses zprint as a library. But feel free to submit a PR as well.

**Comment by filipesilva** [comment]
In my case I wanted to run it on a npm script directly. Something like https://www.npmjs.com/package/foreach-cli can be used together with zprint-clj, it's just a bit more unwieldy.

**Comment by roman01la** [comment]
fixed in 0.5.0

**Comment by filipesilva** [comment]
Hey that was super nice of you, thanks! The "check without writing" mode for CI is also very useful!
