### ISSUE TITLE
`Cannot find module '../out/main'` when trying to run zprint-clj

### ISSUE THREAD

**Issue by miikka** [clj-commons/zprint-clj#7]
Hey, I tried to run zprint-clj, but I'm getting an error. (I tried with `npm i zprint-clj` in addition to using `npx` but the result is the same.)

```
$ npx zprint-clj
Cannot find module '../out/main'
```

This is on macOS 10.14.2, Node 11.9.0, npm 6.7.0, zprint-clj 0.3.0.

**Comment by tmattacchione** [comment]
True.  I reached out to @roman01la and we can look into this.  https://github.com/roman01la/zprint-atom/issues/1

**Comment by roman01la** [comment]
fixed in 0.4.0
